# Generated by Django 2.0.2 on 2018-05-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20180519_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='previewImgPath',
            field=models.ImageField(upload_to='dash'),
        ),
    ]
