# Generated by Django 2.0.2 on 2018-05-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20180519_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='previewImgPath',
            new_name='previewImg',
        ),
    ]
