# Generated by Django 2.0.2 on 2018-05-20 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_auto_20180519_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='previewImg',
            new_name='previewImgPath',
        ),
    ]
